-- Flyway migration: initial schema for beers and orders

-- Table: beer
CREATE TABLE IF NOT EXISTS beer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_name VARCHAR(255),
    beer_style VARCHAR(255),
    upc VARCHAR(255),
    quantity_on_hand INTEGER,
    price DECIMAL(19,2),
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Table: beer_order
CREATE TABLE IF NOT EXISTS beer_order (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    customer_ref VARCHAR(255),
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Table: beer_order_line
CREATE TABLE IF NOT EXISTS beer_order_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_order_id INTEGER NOT NULL,
    beer_id INTEGER NOT NULL,
    order_quantity INTEGER,
    price DECIMAL(19,2),
    created_date TIMESTAMP,
    update_date TIMESTAMP,
    CONSTRAINT fk_bol_order FOREIGN KEY (beer_order_id) REFERENCES beer_order(id),
    CONSTRAINT fk_bol_beer FOREIGN KEY (beer_id) REFERENCES beer(id)
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_bol_order ON beer_order_line(beer_order_id);
CREATE INDEX IF NOT EXISTS idx_bol_beer ON beer_order_line(beer_id);
