-- Flyway migration: add customer table and relation to beer_order

-- Table: customer
CREATE TABLE IF NOT EXISTS customer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(50),
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    postal_code VARCHAR(50) NOT NULL,
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Indexes that can help lookups (non-unique for email)
CREATE INDEX IF NOT EXISTS idx_customer_email ON customer(email);
CREATE INDEX IF NOT EXISTS idx_customer_city ON customer(city);
CREATE INDEX IF NOT EXISTS idx_customer_state ON customer(state);

-- Add customer_id to beer_order and create FK
ALTER TABLE beer_order ADD COLUMN IF NOT EXISTS customer_id INTEGER;

-- Backward compatible: allow NULLs initially. Apps may enforce presence at service level.
ALTER TABLE beer_order
    ADD CONSTRAINT IF NOT EXISTS fk_beer_order_customer
    FOREIGN KEY (customer_id) REFERENCES customer(id)
    ON DELETE RESTRICT;
