-- Flyway migration: add beer_order_shipment table

-- 1) Create table
CREATE TABLE IF NOT EXISTS beer_order_shipment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_order_id INTEGER NOT NULL,
    shipment_date DATE NOT NULL,
    carrier VARCHAR(255) NOT NULL,
    carrier_number VARCHAR(255) NOT NULL,
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- 2) Add foreign key constraint (separate statement per guidelines)
ALTER TABLE beer_order_shipment
    ADD CONSTRAINT fk_bos_order FOREIGN KEY (beer_order_id) REFERENCES beer_order(id);

-- 3) Helpful index for lookups by parent order
CREATE INDEX IF NOT EXISTS idx_bos_order ON beer_order_shipment(beer_order_id);
