-- Flyway migration V3: add customer table and wire to beer_order

-- Create customer table
CREATE TABLE IF NOT EXISTS customer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(50),
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Add customer_id column to beer_order first (if not exists)
ALTER TABLE beer_order ADD COLUMN IF NOT EXISTS customer_id INTEGER;

-- Then add the foreign key constraint separately per guidelines
ALTER TABLE beer_order
    ADD CONSTRAINT IF NOT EXISTS fk_bo_customer FOREIGN KEY (customer_id) REFERENCES customer(id);
